import React from 'react';
import variants from '../data/image-variants.json';

/**
 * Renders a <picture> with AVIF/WebP/raster srcSets for any image that has
 * responsive variants generated by scripts/generate-responsive-variants.py.
 *
 * Blog imagery is data-driven (src/data/blog-index.json -> post.img), so the
 * variant paths cannot be hardcoded in JSX the way the Home hero does it.
 * This component looks the source path up in the generated manifest and emits
 * exactly the same markup shape. Images with no manifest entry fall through to
 * a plain <img>, so it is safe to use everywhere.
 *
 * The original file is always kept as the final fallback in the chain.
 */
export default function ResponsiveImage({ src, alt, sizes = '100vw', ...imgProps }) {
    const entry = src ? variants[src] : null;

    if (!entry || !entry.variants || entry.variants.length === 0) {
        return <img src={src} alt={alt} {...imgProps} />;
    }

    const srcSetFor = (key) =>
        entry.variants.map((v) => `${v[key]} ${v.w}w`).join(', ');

    return (
        <picture>
            <source type="image/avif" srcSet={srcSetFor('avif')} sizes={sizes} />
            <source type="image/webp" srcSet={srcSetFor('webp')} sizes={sizes} />
            <source type={entry.fallbackType} srcSet={srcSetFor('raster')} sizes={sizes} />
            <img
                src={src}
                srcSet={srcSetFor('raster')}
                sizes={sizes}
                alt={alt}
                width={entry.width}
                height={entry.height}
                {...imgProps}
            />
        </picture>
    );
}
